blank_issues_enabled: false
contact_links:
  - name: Question / usage help
    url: https://github.com/SebiShepherd/nextcloud_tasks_android/discussions
    about: For questions and general help, please start a discussion instead of opening an issue.
